### ISSUE TITLE
Can't pass more then one parameter by the url

### ISSUE THREAD

**Issue by NelsonMedinaSilva** [mike1808/3dviewer#1]
Greeting. Im trying to pass my obj to the loader using parameters on the url: a token and a reference. To do so, Im using react's routing. The issue is, when I try to pass them individualy, I get an error about the zip. Any idea how to solve this ?

url exemple:

localhost:3000/token/reference

Error:

![30421620_1620829917953360_1265277343_n](https://user-images.githubusercontent.com/22938153/38546355-54c6ba64-3ca4-11e8-81bd-c8278ec8cd1c.png)

Code:

import React, {Component} from 'react';
import './App.css';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import { BrowserRouter as Router, Route } from 'react-router-dom'

import Viewer from '../Viewer/Viewer';

class App extends Component {

    render() {
        return (

           <Router className="App">
                <Route path="/:token/:reference" component={Viewer}/>
            </Router>
        );
    }
}
export default App;

Thanks !

**Comment by mike1808** [comment]
hi @NelsonMedinaSilva 
I guess you placed `zip/zip.js` lib which handles unzipping in a wrong place and it downloaded an `html` (inferring from SyntaxError).

**Comment by NelsonMedinaSilva** [comment]
@mike1808 I left zip.js where you did, In public/index.html.

...
	    <script src="zip/zip.js"></script>
    <script>
      zip.workerScriptsPath = '/zip/';
    </script>
  </body>

**Comment by mike1808** [comment]
@NelsonMedinaSilva please have a look what you receive from the server when you fetch `zip.js`  (open DevTools and Network tab)

**Comment by NelsonMedinaSilva** [comment]
![30232186_1621089624594056_515879559_o](https://user-images.githubusercontent.com/22938153/38563487-e7c99d1a-3cd4-11e8-9444-abdcf2f9de19.png)

@mike1808  this ?

**Comment by mike1808** [comment]
@NelsonMedinaSilva yes, see that you received html, if you go to response you will what exactly you received

**Comment by NelsonMedinaSilva** [comment]
@mike1808 its solved, thanks !
